Search various possible paths for supercollider headers

diff --git a/scripts.lin/supercollider b/scripts.lin/supercollider
--- a/scripts.lin/supercollider
+++ b/scripts.lin/supercollider
@@ -11,7 +11,27 @@
 # Supercollider headers : path to the folder containing :
 # plugin_interface/, common/ and server/ headers
 
-SC="/usr/local/include/SuperCollider"
+# Possible path
+
+SC0="/usr/include/SuperCollider"
+SC1="/usr/include/supercollider"
+SC2="/usr/local/include/SuperCollider"
+SC3="/usr/local/include/supercollider"
+
+# check if directory exists
+
+if [ -d $SC0 ]; then
+	SC=$SC0
+elif [ -d $SC1 ]; then
+	SC=$SC1
+elif [ -d $SC2 ]; then
+	SC=$SC2
+elif [ -d $SC3 ]; then
+	SC=$SC3
+else 
+	echo "Can't find SuperCollider headers"
+	exit 1
+fi 
 
 INCLUDE="-I$SC/plugin_interface/ -I$SC/common/ -I$SC/server/"
 
@@ -58,10 +78,10 @@ done
 #
 if [[ $(uname) == Darwin ]]; then
     EXT="scx"
-	SCFLAGS="-DSC_DARWIN -bundle "
+	SCFLAGS="-DSC_DARWIN -DNDEBUG -bundle "
 elif [[ $(uname) == Linux ]]; then
     EXT="so"
-	SCFLAGS="-DSC_LINUX -shared -fPIC"
+	SCFLAGS="-DSC_LINUX -DNDEBUG -shared -fPIC"
 else
 	echo "unsupported plateform"
 	exit 1
@@ -90,7 +110,7 @@ for p in $FILES; do
     (
         cd "$TMP"
         faust2sc $f.xml > "${f%.dsp}.sc" 2>/dev/null
-        ${CXX=g++}  -O3 $SCFLAGS $INCLUDE $CXXFLAGS $OMP -DNDEBUG -Dmydsp=${f%.dsp} -o ${f%.dsp}.$EXT ${f%.dsp}.cpp
+        ${CXX=g++}  -O3 $SCFLAGS $INCLUDE $CXXFLAGS $OMP -Dmydsp=${f%.dsp} -o ${f%.dsp}.$EXT ${f%.dsp}.cpp
     )> /dev/null
 
     ## move the produced files from tmp to source dir
diff --git a/scripts.osx/supercollider b/scripts.osx/supercollider
--- a/scripts.osx/supercollider
+++ b/scripts.osx/supercollider
@@ -10,10 +10,30 @@
 #-------------------------------------------------------------------
 # Supercollider headers : path to the folder containing :
 # plugin_interface/, common/ and server/ headers
- 
-SC="/usr/local/include/supercollider"
 
-INCLUDE="-I$SC/plugin_interface/ -I$SC/common/ -I$SC/server/ -I$SC/lang/"
+# Possible path
+
+SC0="/usr/include/SuperCollider"
+SC1="/usr/include/supercollider"
+SC2="/usr/local/include/SuperCollider"
+SC3="/usr/local/include/supercollider"
+
+# check if directory exists
+
+if [ -d $SC0 ]; then
+	SC=$SC0
+elif [ -d $SC1 ]; then
+	SC=$SC1
+elif [ -d $SC2 ]; then
+	SC=$SC2
+elif [ -d $SC3 ]; then
+	SC=$SC3
+else 
+	echo "Can't find SuperCollider headers"
+	exit 1
+fi 
+
+INCLUDE="-I$SC/plugin_interface/ -I$SC/common/ -I$SC/server/"
 
 #-------------------------------------------------------------------
 # Analyze command arguments :
@@ -58,10 +78,10 @@ done
 #
 if [[ $(uname) == Darwin ]]; then
     EXT="scx"
-	SCFLAGS="-DSC_DARWIN -bundle "
+	SCFLAGS="-DSC_DARWIN -DNDEBUG -bundle "
 elif [[ $(uname) == Linux ]]; then
     EXT="so"
-	SCFLAGS="-DSC_LINUX -shared -fPIC"
+	SCFLAGS="-DSC_LINUX -DNDEBUG -shared -fPIC"
 else
 	echo "unsupported plateform"
 	exit 1
